# -*- coding: utf-8 -*-
"""Set Default Raw Value.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16iReXnJd4J84hCvdzyoYHoTGJo1zsq_L
"""

import pandas as pd
import pymysql
from sqlalchemy import create_engine
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

conn = pymysql.connect(host='34.64.224.44', user='root', password='A412GBVSDsawe%$we', db='smart_factory')
sql_state='SELECT * FROM `current_stock_raw`'
df=pd.read_sql_query(sql_state, conn)

sql_state='SELECT * FROM `stock_raw`'
stock_raw=pd.read_sql_query(sql_state, conn)

now=datetime.now().strftime('%Y-%m-%d')

stock_raw=stock_raw.loc[stock_raw['SOLDDATE']==now]

for raw in df['raw_material'].unique():
  df.loc[df['raw_material']==raw,'raw_stock'] = stock_raw[raw].values.astype('int32')

db_connection_str = 'mysql+pymysql://root:A412GBVSDsawe%$we@34.64.224.44:3306/smart_factory'
db_connection = create_engine(db_connection_str)
conn = db_connection.connect() 

df.to_sql(name = 'current_stock_raw',con = db_connection, index = False, if_exists = 'replace')

print('complete')