# -*- coding: utf-8 -*-
"""Set Default Raw Value.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16iReXnJd4J84hCvdzyoYHoTGJo1zsq_L
"""

import pandas as pd
import pymysql
from sqlalchemy import create_engine
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

conn = pymysql.connect(host='34.64.224.44', user='root', password='A412GBVSDsawe%$we', db='smart_factory')
sql_state='SELECT * FROM `current_stock_raw`'
df=pd.read_sql_query(sql_state, conn)

sql_state='SELECT * FROM `safety_stock`'
safety_stock=pd.read_sql_query(sql_state, conn)

raw_list=[2834834,
 1141595,
 200855,
 163682,
 9065,
 93519,
 352725,
 96841,
 4201,
 201345,
 154635,
 3434,
 51497,
 24965,
 107205,
 42387,
 98214,
 59847,
 8512,
 450333,
 3241,
 4201,
 418,
 551,
 351,
 6178,
 7066,
 42447,
 3152,
 45375,
 1518,
 1503,
 4511,
 1296,
 444]

while True:
  try:
    choice = int(input('1) Safety_stock 2) Default 3) Custom : '))
    break 
  except ValueError:
    print("Please enter numbers only")

if choice == 1:
  df['raw_stock'] = safety_stock['safety_stock']

elif choice == 2:
  for i in range(0,35):
    df['raw_stock'][i] = raw_list[i]

elif choice == 3:
  for raw in df['raw_material'].unique():
    while True:
      try:
        number = int(input(f'{raw} value :'))
        break 
      except ValueError:
        print("Please enter numbers only")
    df.loc[df['raw_material']==raw,'raw_stock'] = number

df

db_connection_str = 'mysql+pymysql://root:A412GBVSDsawe%$we@34.64.224.44:3306/smart_factory'
db_connection = create_engine(db_connection_str)
conn = db_connection.connect() 

df.to_sql(name = 'current_stock_raw',con = db_connection, index = False, if_exists = 'replace')

print('Complete')